---
title: "Raster Polygonizer Workflow"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Raster Polygonizer Workflow}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
library(rasterpolygonizer)

if (!requireNamespace("sf", quietly = TRUE)) stop("Install 'sf' to run this vignette")
if (!requireNamespace("terra", quietly = TRUE)) stop("Install 'terra' to run this vignette")
#if (!requireNamespace("rmapshaper", quietly = TRUE)) stop("Install 'rmapshaper' to run this vignette")


```

```{r message=FALSE, warning=FALSE}
library(ggplot2)


load_extdata <- function(filename, pkg = "rasterpolygonizer") {
  path <- system.file("extdata", filename, package = pkg)
  if (path == "") stop(sprintf("File '%s' not found in inst/extdata", filename))
  path
}

r <- terra::rast(load_extdata("sample_raster.tif"))
b <- sf::st_read(load_extdata("sample_buildings.gpkg"), quiet = TRUE)

r_df_raw <- as.data.frame(r, xy = TRUE, na.rm = TRUE)
names(r_df_raw)[3] <- "value"

ggplot(r_df_raw) +
  geom_raster(aes(x = x, y = y, fill = value)) +
  coord_equal() +
  scale_fill_viridis_c(na.value = "transparent") +
  theme_minimal() +
  labs(title = "Input raster")

r_filled <- fill_ground_raster(r)

r_df_filled <- as.data.frame(r_filled, xy = TRUE, na.rm = TRUE)
names(r_df_filled)[3] <- "value"

ggplot(r_df_filled) +
  geom_raster(aes(x = x, y = y, fill = value)) +
  coord_equal() +
  scale_fill_viridis_c(na.value = "transparent") +
  theme_minimal() +
  labs(title = "Filled ground raster")

edges <- extract_building_edges_to_polygons(r_filled, thr_prob = .75)

# Use raster extent as mask for this example
mask_poly <- terra::as.polygons(r)
mask_sf <- sf::st_as_sf(mask_poly)

buildings_sf <- clean_building_polygons(
  closed_edges = edges$closed_edges,
  shrink_dist = -0.5,
  simplify_tol = 2.5,
  min_area = 19.99,
  max_area = 2000
)

# Print summary



r_df <- as.data.frame(r_filled, xy = TRUE, na.rm = TRUE)
names(r_df)[3] <- "value"
ggplot() +
  geom_raster(
    data = r_df,
    aes(x = x, y = y, fill = value)
  ) +
  geom_sf(
    data = buildings_sf,
    fill = NA,
    color = "red",
    linewidth = 0.6
  ) +
  coord_sf() +
  scale_fill_viridis_c(na.value = "transparent") +
  theme_minimal()



```


```{r message=FALSE, warning=FALSE}

terra::crs(r) <- "EPSG:32606"
r_crs <- terra::crs(r)

buildings_sf <- sf::st_set_crs(buildings_sf, r_crs)
b <- sf::st_set_crs(b, r_crs)

filtered <- filter_by_ground_truth(
  buildings_sf,
  b,
  threshold = 0.5
)

r_df <- as.data.frame(r_filled, xy = TRUE, na.rm = TRUE)
names(r_df)[3] <- "value"
ggplot() +
  geom_raster(
    data = r_df,
    aes(x = x, y = y, fill = value)
  ) +
  geom_sf(
    data = filtered,
    fill = NA,
    color = "red",
    linewidth = 0.6
  ) +
  coord_sf() +
  scale_fill_viridis_c(na.value = "transparent") +
  theme_minimal()

```



